In [17]:
using LinearAlgebra
using Statistics

In [1]:
# matrix test

a = [1 2 3 4;
0 0 1 2]

2×4 Array{Int64,2}:
 1  2  3  4
 0  0  1  2

In [2]:
v = [1,0]

2-element Array{Int64,1}:
 1
 0

In [4]:
a.*v

2×4 Array{Int64,2}:
 1  2  3  4
 0  0  0  0

In [18]:
# sum over each row
sum(a,dims=2)

2×1 Array{Int64,2}:
 10
  3

In [19]:
?sum

search: sum sum! summary cumsum cumsum! isnumeric VersionNumber issubnormal



```
sum(f, itr)
```

Sum the results of calling function `f` on each element of `itr`.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

# Examples

```jldoctest
julia> sum(abs2, [2; 3; 4])
29
```

Note the important difference between `sum(A)` and `reduce(+, A)` for arrays with small integer eltype:

```jldoctest
julia> sum(Int8[100, 28])
128

julia> reduce(+, Int8[100, 28])
-128
```

In the former case, the integers are widened to system word size and therefore the result is 128. In the latter case, no such widening happens and integer overflow results in -128.

---

```
sum(itr)
```

Returns the sum of all elements in a collection.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

# Examples

```jldoctest
julia> sum(1:20)
210
```

---

```
sum(A::AbstractArray; dims)
```

Sum elements of an array over the given dimensions.

# Examples

```jldoctest
julia> A = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> sum(A, dims=1)
1×2 Array{Int64,2}:
 4  6

julia> sum(A, dims=2)
2×1 Array{Int64,2}:
 3
 7
```
