In [13]:
using Random

In [35]:
include("../src/ProcGA.jl")

Main.ProcGA

In [10]:
l1 = append!(zeros(Int,5),collect(1:5));

In [16]:
gs = [l1,copy(l1),copy(l1)]

3-element Array{Array{Int64,1},1}:
 [0, 1, 3, 0, 5, 0, 0, 2, 4, 0]
 [0, 1, 3, 0, 5, 0, 0, 2, 4, 0]
 [0, 1, 3, 0, 5, 0, 0, 2, 4, 0]

In [36]:
shuffle!.(gs)

3-element Array{Array{Int64,1},1}:
 [3, 1, 0, 2, 4, 0, 0, 0, 5, 0]
 [2, 5, 0, 1, 3, 0, 4, 0, 0, 0]
 [2, 0, 0, 1, 0, 0, 0, 3, 4, 5]

In [38]:
ProcGA.columnsortjob!(gs)

3-element Array{Array{Int64,1},1}:
 [0, 2, 0, 0, 1, 3, 4, 5, 0, 0]
 [0, 1, 4, 0, 5, 2, 3, 0, 0, 0]
 [3, 1, 0, 5, 0, 2, 0, 4, 0, 0]

In [9]:
l1

10-element Array{Int64,1}:
 0
 0
 0
 0
 0
 1
 2
 3
 4
 5

In [5]:
# consequtive use limit 
# if id continues more than lmt give penalty
function pencontinuity(lst::Array{Int,1},id,lmt)
    ln = length(lst)
    p = zeros(Int,ln)
    chk = [(x == id ? 1 : 0) for x in lst]
    
    cnt = 0
    x0 = 0
    for i in 1:ln
        x = chk[i]
        if x > 0
            cnt += 1
            p[i] = cnt
        else
            cnt = 0
        end
    end
    
    [ x > lmt ? (x-lmt) : 0 for x in p]
end

pencontinuity (generic function with 1 method)

In [8]:
l1 = vcat(repeat([1],5),[0,0,1,1,0,0])

11-element Array{Int64,1}:
 1
 1
 1
 1
 1
 0
 0
 1
 1
 0
 0

In [9]:
pencontinuity(l1,1,3)

11-element Array{Int64,1}:
 0
 0
 0
 1
 2
 0
 0
 0
 0
 0
 0

In [18]:
pl = ProcGA.listcontinuity([l1,l1],1,3)

2-element Array{Array{Int64,1},1}:
 [0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0]

In [25]:
sum(sum.(pl))

6

In [13]:
[l1,l1] .+ [l1,-l1]

2-element Array{Array{Int64,1},1}:
 [2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [14]:
?sum

search: sum sum! summary cumsum cumsum! isnumeric VersionNumber issubnormal



MethodError: MethodError: no method matching latex(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Markdown.HorizontalRule)
Closest candidates are:
  latex(::IO, !Matched::Markdown.Table) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Markdown/src/GitHub/table.jl:154
  latex(::IO, !Matched::Markdown.LaTeX) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Markdown/src/IPython/IPython.jl:28
  latex(::IO, !Matched::Markdown.MD) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Markdown/src/render/latex.jl:19
  ...