# ProcGA tutorial

How to use ProcGA.

In [22]:
include("../src/ProcGA.jl")

Main.ProcGA

## set basic table

This module does genetic evolution based on given table(Array{Int,2}).

You must give a source table to define as gene.

A table must have sufficient 0 element to do enough mutation of shuffling.

In [15]:
g0 = reshape([repeat([0,0],6); repeat([1,2,2,1],3); ],(2,12))

2×12 Array{Int64,2}:
 0  0  0  0  0  0  1  2  1  2  1  2
 0  0  0  0  0  0  2  1  2  1  2  1

In [16]:
ProcGA.orderjob!(g0)

2×12 Array{Int64,2}:
 0  0  0  0  0  0  1  1  1  2  2  2
 0  0  0  0  0  0  1  1  1  2  2  2

## define penalty function

Give a penalty so that it is smaller when each columns have one items only.

In [18]:
length(g0)

24

In [79]:
function mypenalty(t::Array{Int,2})
    p = 0
    r,c = size(t)
    for i in 1:c
        v = t[:,i]
        if sum(v) > 0
            s = v[v.>0]
            p += length(s)^2
        end
    end
    # add paired product 
    for i in 1:r
        for j in 1:c-1
            p += t[i,j]*t[i,j+1]
        end
    end
    p
end

mypenalty (generic function with 1 method)

In [80]:
ProcGA.penalty(t) = mypenalty(t)

In [81]:
ProcGA.penalty(g0)

48

## make initial population

There is 2 method to populate genes.
One is `populatefrom` the other is `populateshuffle`.

`populatefrom` uses a base table as a master and make a mutation from it to fill up population.

`populateshuffle` uses a base table shuffling its contents rowwise.

In [39]:
pp1 = ProcGA.populatefrom(g0,50);

50-element Array{Array{Int64,2},1}:
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 1 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 1; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 1 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 1 0 … 2 2]
 ⋮                     
 [0 0 … 1 2; 2 0 … 0 2]
 [0 2 … 2 0; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 1 0 … 2 2]
 [0 0 … 2 2; 2 0 … 2 2]
 [0 0 … 1 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]
 [0 0 … 2 2; 0 0 … 2 2]

In [40]:
pp2 = ProcGA.populateshuffle(g0,150);

50-element Array{Array{Int64,2},1}:
 [0 0 … 2 2; 0 0 … 2 2]
 [2 1 … 0 1; 2 0 … 0 2]
 [0 0 … 0 1; 0 0 … 1 2]
 [2 2 … 1 1; 1 1 … 2 0]
 [2 0 … 0 2; 0 0 … 0 0]
 [1 2 … 1 0; 1 0 … 1 2]
 [2 0 … 0 0; 1 0 … 2 0]
 [2 0 … 1 0; 0 2 … 1 0]
 [1 0 … 0 0; 2 1 … 0 0]
 [0 1 … 0 0; 0 0 … 1 2]
 [1 2 … 0 2; 1 2 … 0 1]
 [0 0 … 2 0; 0 0 … 0 1]
 [0 0 … 0 0; 1 0 … 0 1]
 ⋮                     
 [0 0 … 2 0; 1 0 … 0 0]
 [1 1 … 0 0; 0 1 … 0 0]
 [1 0 … 1 2; 0 0 … 2 1]
 [2 0 … 2 0; 0 2 … 0 1]
 [2 2 … 0 0; 0 1 … 1 0]
 [0 2 … 2 2; 2 0 … 1 0]
 [2 1 … 1 2; 0 0 … 2 1]
 [2 0 … 0 2; 0 0 … 1 0]
 [0 0 … 0 1; 0 2 … 2 2]
 [0 0 … 1 0; 1 1 … 2 0]
 [2 0 … 0 0; 0 0 … 1 2]
 [0 0 … 1 0; 0 1 … 2 0]

In [84]:
pp = vcat(pp1,pp2);

## evolution

Proceed generations by doing sort, die, birth, mutate cycles.

Each time, population is sorted by their penalty order.

In [101]:
# population, generation, print interval, survive rate, elite rate, mutant rate.
vl = ProcGA.evolution!(pp,1000,100,0.8,0.2,0.05);

i:10 => [14, 14, 30]
i:20 => [14, 14, 32]
i:30 => [14, 14, 30]
i:40 => [14, 14, 34]
i:50 => [14, 14, 34]
i:60 => [14, 14, 35]
i:70 => [14, 14, 32]
i:80 => [14, 14, 34]
i:90 => [14, 14, 31]
i:100 => [14, 14, 29]
i:110 => [14, 14, 34]
i:120 => [14, 14, 30]
i:130 => [14, 14, 27]
i:140 => [12, 14, 32]
i:150 => [12, 14, 28]
i:160 => [12, 14, 31]
i:170 => [12, 12, 32]
i:180 => [12, 12, 31]
i:190 => [12, 12, 31]
i:200 => [12, 12, 28]


In [ ]:
using Plots, PyPlot

┌ Info: Recompiling stale cache file C:\Users\hp\.julia\compiled\v1.0\PyPlot\oatAj.ji for PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
└ @ Base loading.jl:1190
┌ Info: Installing matplotlib via the Conda matplotlib package...
└ @ PyCall C:\Users\hp\.julia\packages\PyCall\0jMpb\src\PyCall.jl:653
┌ Info: Running `conda install -y matplotlib` in root environment
└ @ Conda C:\Users\hp\.julia\packages\Conda\uQitS\src\Conda.jl:112


Solving environment: ...working... done


six-1.11.0           | 21 KB     | ########## | 100% 
pip-18.1             | 1.8 MB    | ########## | 100% 
mkl_random-1.0.1     | 267 KB    | ########## | 100% 
pyparsing-2.3.0      | 102 KB    | ########## | 100% 
setuptools-40.5.0    | 630 KB    | ########## | 100% 
tornado-5.1.1        | 665 KB    | ########## | 100% 
pyqt-5.9.2           | 4.2 MB    | ########## | 100% 
matplotlib-3.0.1     | 6.5 MB    | ########## | 100% 
pytz-2018.7          | 257 KB    | ########## | 100% 
kiwisolver-1.0.1     | 61 KB     | ########## | 100% 
sip-4.19.8           | 281 KB    | ########## | 100% 
python-dateutil-2.7. | 276 KB    | ########## | 100% 
wincertstore-0.2     | 13 KB     | ########## | 100% 
freetype-2.9.1       | 470 KB    | ########## | 100% 
certifi-2018.10.15   | 138 KB    | ########## | 100% 
numpy-base-1.15.4    | 3.9 MB    | ########## | 100% 
numpy-1.15.4         | 36 KB     | ########## | 100% 
wheel-0.32.2         | 52 KB     | ########## | 100% 
python-3.7.1         | 19.4 


## Package Plan ##

  environment location: C:\Users\hp\.julia\conda\3

  added / updated specs: 
    - matplotlib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    six-1.11.0                 |           py37_1          21 KB
    pip-18.1                   |           py37_0         1.8 MB
    mkl_random-1.0.1           |   py37h77b88f5_1         267 KB
    pyparsing-2.3.0            |           py37_0         102 KB
    setuptools-40.5.0          |           py37_0         630 KB
    tornado-5.1.1              |   py37hfa6e2cd_0         665 KB
    pyqt-5.9.2                 |   py37h6538335_2         4.2 MB
    matplotlib-3.0.1           |   py37hc8f65d3_0         6.5 MB
    pytz-2018.7                |           py37_0         257 KB
    kiwisolver-1.0.1           |   py37h6538335_0          61 KB
    sip-4.19.8                 |   py37h6538335_0         281 KB
    python-dateutil-2.7

cycler-0.10.0        | 13 KB     | ########## | 100% 

done
Verifying transaction: ...working... 

In [ ]:
pyplot()

In [ ]:
y = (x->x[1]).(vl)
x = collect(1:length(y));

In [94]:
plot(x,y)

ErrorException: error compiling _plot!: error compiling _display: could not load library "libGR.dll"
The specified module could not be found.


## saving result, etc.

In [95]:
bst = pp[1]

2×12 Array{Int64,2}:
 1  0  0  1  1  0  2  0  2  0  2  0
 0  1  1  0  0  1  0  2  0  2  0  2

In [54]:
pp[1]

2×12 Array{Int64,2}:
 1  1  1  2  2  2  0  0  0  0  0  0
 0  1  1  1  2  2  2  0  0  0  0  0